<template>
  <div class="home-title">
    <h1>The Community Showcase</h1>
    <p>Browse through a collection of imaginative and visually stunning images generated by DALL-E</p>
  </div>
  <div class="search-input">
    <div class="input-wrapper">
      <div class="label-container">
        <label for="search">
          Search posts
        </label>
      </div>
      <input
        type="text"
        id="search"
        name="search"
        placeholder="search post.."
        required
        v-model="searchText"
      />
    </div>
    <div class="mt-10">
      <div class="flex justify-center items-center" v-if="loading">
        <Loader class="loader" />
      </div>
      <div v-else>
        <h2 v-show="searchText.length > 0">Showing results for: <span>{{ searchText }}</span></h2>
        <template v-if="filteredPosts?.length > 0">
          <div class="cards-wrapper">
            <Card v-for="(post,i) in filteredPosts" :post="post" :key="i" />
          </div>
        </template>
        <h2 v-else class="title">
          {{ title }}
        </h2>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue';
import Loader from '../components/Loader.vue';
import Card from '../components/Card.vue';

const searchText = ref('');
const loading = ref(false);
const allPosts = ref([]);
const title = ref('');

const getAllPosts = async () => {
  loading.value = true;
  try {
    const response = await fetch('https://dalle-4yj8.onrender.com/api/v1/post', {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
      }
    })

    const results = await response.json();
    if (results.success) {
      if (results.data.length == 0) {
        title.value = 'No posts yet.'
      } else {
        allPosts.value = results.data;
      }
    }
  } catch (error) {
    console.log(error);
  } finally {
    loading.value = false;
  }
}

const filteredPosts = computed(() => {
  if (searchText.value == "") {
    return allPosts.value;
  } else {
    const result = allPosts.value.filter((item) =>
      item.name.toLowerCase().includes(searchText.value.toLowerCase())
      || item.prompt.toLowerCase().includes(searchText.value.toLowerCase())
    )
    if (result.length == 0) {
      title.value = 'No Search result found'
    } else {
      return result;
    }
  }
});

onMounted(async () => {
  await getAllPosts();
});

</script>

